### ISSUE TITLE
running Nvidia-docker will say "Unknown runtime specified nvidia"

### ISSUE THREAD

**Issue by xiaoyongzhu** [wbuchwalter/tensorflow-k8s-azure#35]
following the official doc here solves the problem for me:
https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#why-do-i-get-the-error-unknown-runtime-specified-nvidia
I suggest we add that in the doc as an FAQ

**Comment by xiaoyongzhu** [comment]
BTW I am following this section: https://github.com/wbuchwalter/tensorflow-k8s-azure/tree/master/1-docker

**Comment by wbuchwalter** [comment]
Are this the steps that you followed to fix this issue: https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup ?

**Comment by xiaoyongzhu** [comment]
Yes. Specifically I am using the “systemd drop in file” approach.

sudo mkdir -p /etc/systemd/system/docker.service.d
sudo tee /etc/systemd/system/docker.service.d/override.conf <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime
EOF
sudo systemctl daemon-reload
sudo systemctl restart docker


I also found that simply restarting docker (sudo systemctl restart docker) will also help, so I suspect this won’t require passing a file to systemd.

Thanks!
Xiaoyong

**Comment by wbuchwalter** [comment]
Thanks!
