### ISSUE TITLE
TfPort missing

### ISSUE THREAD

**Issue by TsuyoshiUshio** [wbuchwalter/tensorflow-k8s-azure#36]
On the module 6, 
https://github.com/wbuchwalter/tensorflow-k8s-azure/tree/master/6-distributed-tensorflow 

The introduction said 

```
TfReplicaSpec Object

Note the last two parameters IsDefaultPS and TfPort that we didn't talk about before.
```
however, we can't find the definition of TfPort. I try to find on the k8s tensorflow however, I couldn't find it as well. sorry this is not a pull request.

**Comment by wbuchwalter** [comment]
Thanks, I removed the reference to TfPort as it is not useful for the workshop.
For information TfPort is just the port on which the different workers and parameter servers communicate, it defaults to `2222`.
